In [1]:
# create list
list1=[1,2,3,4]
list2=[2,3,4,5]

In [2]:
#add items of list2 to last of list1
list1+list2

[1, 2, 3, 4, 2, 3, 4, 5]

In [3]:
#add corresponding items 
list3=[]
for i,j in zip(list1,list2):
    list3.append(i+j)
print(list3)

[3, 5, 7, 9]


# numpy

In [4]:
import numpy as np

In [11]:
#convert list as array
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4])

In [13]:
arr2=np.array(list2)
arr2

array([2, 3, 4, 5])

In [14]:
#sum of 2 arrays
sum1 = arr1+arr2
sum1

array([3, 5, 7, 9])

In [16]:
#code to get veriable details
%whos

Variable   Type       Data/Info
-------------------------------
arr1       ndarray    4: 4 elems, type `int32`, 16 bytes
arr2       ndarray    4: 4 elems, type `int32`, 16 bytes
i          int        4
j          int        5
list1      list       n=4
list2      list       n=4
list3      list       n=4
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
sum1       ndarray    4: 4 elems, type `int32`, 16 bytes


In [17]:
#create a list of list
data2=[[1,2,3,4],[5,6,7,8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [19]:
#convert list to array
arr3=np.array(data2)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
#dimension of an array
arr3.ndim

2

In [22]:
#datatype of an array
arr3.dtype

dtype('int32')

In [23]:
#shape of an array
arr3.shape

(2, 4)

In [24]:
#change datatype of an array
arr4=np.array(data2,float)
arr4

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [25]:
arr4.dtype

dtype('float64')

In [26]:
#string datatype is represented as U1 or unique code datatype
arr5=np.array(['1','2','3','5'])
arr5

array(['1', '2', '3', '5'], dtype='<U1')

In [28]:
arr6=np.array(arr5,int)
arr6

array([1, 2, 3, 5])

In [31]:
arr6.dtype

dtype('int32')

In [34]:
#arange function for array is same as range in list
arr7=np.arange(4,20)
arr7

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
#arange with step
arr8=np.arange(4,20,2)
arr8

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
#Reshape function..product of rows and colums should equals to the number of elements
arr9=arr8.reshape(4,2)
arr9

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [39]:
arr10=arr8.reshape(2,4)
arr10

array([[ 4,  6,  8, 10],
       [12, 14, 16, 18]])

In [40]:
#Linspace function..it is used to split the interwel to equal inervals
arr11=np.linspace(1,30,5)
arr11

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [44]:
arr12=np.linspace(0,12,3)
arr12

array([ 0.,  6., 12.])

In [45]:
#more operations on array
arr=np.arange(5,20)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
arr[5:12]

array([10, 11, 12, 13, 14, 15, 16])

In [49]:
arr[5]

10

In [51]:
arr[5:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
arr[:5]

array([5, 6, 7, 8, 9])

In [53]:
#get elemets of more than 2 specified indexes
arr[[1,3,5]]

array([ 6,  8, 10])

In [54]:
arr13=np.array([[-7,5,-2,4],[5,2,7,3],[-13,10,3,-5]])
arr13

array([[ -7,   5,  -2,   4],
       [  5,   2,   7,   3],
       [-13,  10,   3,  -5]])

In [55]:
#to get elements of 3rd row
arr13[2]

array([-13,  10,   3,  -5])

In [56]:
arr13[0]

array([-7,  5, -2,  4])

In [57]:
arr13[[0,1]]

array([[-7,  5, -2,  4],
       [ 5,  2,  7,  3]])

In [58]:
#to get coloms
arr13[:,1]

array([ 5,  2, 10])

In [59]:
arr13[:,3]

array([ 4,  3, -5])

In [60]:
#to get a specified index element
arr13[1,1]

2

In [61]:
arr14=np.arange(10,82,2)
arr14

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [62]:
len(arr14)

36

In [64]:
arr14=arr14.reshape(6,6)
arr14

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [65]:
#to get all the elements of colum 1 and 3
arr14[:,[0,2]]

array([[10, 14],
       [22, 26],
       [34, 38],
       [46, 50],
       [58, 62],
       [70, 74]])

In [66]:
#to get all the values of coloms from 1 to 3
arr14[:,0:3]

array([[10, 12, 14],
       [22, 24, 26],
       [34, 36, 38],
       [46, 48, 50],
       [58, 60, 62],
       [70, 72, 74]])

In [67]:
#to get all the values of rows from 1 to 3
arr14[:3,:]

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44]])

In [68]:
#sum of all elements of array using builtin function and function from numpy
arr14.sum()

1620

In [69]:
np.sum(arr14)

1620

In [70]:
#mean
arr14.mean()

45.0

In [71]:
np.mean(arr14)

45.0

In [72]:
#median...no builtin function for median..so use numpy function
np.median(arr14)

45.0

In [75]:
#operations on axis...x axis =1 and y axis =0
arr14.sum(axis=1)

array([ 90, 162, 234, 306, 378, 450])

In [76]:
arr14.sum(1)

array([ 90, 162, 234, 306, 378, 450])

In [74]:
arr14.sum(axis=0)

array([240, 252, 264, 276, 288, 300])

In [77]:
arr14.sum(0)

array([240, 252, 264, 276, 288, 300])

In [78]:
#scalar operations...add 5 to all elements in the array
arr14+5

array([[15, 17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35, 37],
       [39, 41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59, 61],
       [63, 65, 67, 69, 71, 73],
       [75, 77, 79, 81, 83, 85]])

In [79]:
arr14-5

array([[ 5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27],
       [29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51],
       [53, 55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73, 75]])

In [80]:
arr14*5

array([[ 50,  60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150, 160],
       [170, 180, 190, 200, 210, 220],
       [230, 240, 250, 260, 270, 280],
       [290, 300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390, 400]])

In [81]:
arr14/5

array([[ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ],
       [ 4.4,  4.8,  5.2,  5.6,  6. ,  6.4],
       [ 6.8,  7.2,  7.6,  8. ,  8.4,  8.8],
       [ 9.2,  9.6, 10. , 10.4, 10.8, 11.2],
       [11.6, 12. , 12.4, 12.8, 13.2, 13.6],
       [14. , 14.4, 14.8, 15.2, 15.6, 16. ]])

In [83]:
#replace all the values in a specified row
arr14[5]=-9
arr14

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [-9, -9, -9, -9, -9, -9]])

In [84]:
#absolute function...neglect all the -ve values inside the array
np.abs(arr14)

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [ 9,  9,  9,  9,  9,  9]])

In [85]:
arr14

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [-9, -9, -9, -9, -9, -9]])

In [86]:
arr14=np.abs(arr14)
arr14

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [ 9,  9,  9,  9,  9,  9]])

In [87]:
#square root function
np.sqrt(arr14)

array([[3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
        4.47213595],
       [4.69041576, 4.89897949, 5.09901951, 5.29150262, 5.47722558,
        5.65685425],
       [5.83095189, 6.        , 6.164414  , 6.32455532, 6.4807407 ,
        6.63324958],
       [6.78232998, 6.92820323, 7.07106781, 7.21110255, 7.34846923,
        7.48331477],
       [7.61577311, 7.74596669, 7.87400787, 8.        , 8.1240384 ,
        8.24621125],
       [3.        , 3.        , 3.        , 3.        , 3.        ,
        3.        ]])

In [88]:
#to get the type
type(arr14)

numpy.ndarray

In [89]:
#to print an array with all values as zero
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [90]:
#to print an array with all values as ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
#identity matrix
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [93]:
#Dot product...(number of coloumns of 1st matrix should be equal to the number of rows of 2nd matrix)
A=np.arange(8).reshape(2,4)
B=np.arange(8).reshape(4,2)
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [94]:
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [95]:
A.dot(B)

array([[28, 34],
       [76, 98]])

In [96]:
#Transpose..it interchange rows and columns
arr14.T

array([[10, 22, 34, 46, 58,  9],
       [12, 24, 36, 48, 60,  9],
       [14, 26, 38, 50, 62,  9],
       [16, 28, 40, 52, 64,  9],
       [18, 30, 42, 54, 66,  9],
       [20, 32, 44, 56, 68,  9]])